/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'text' : string,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface ConversationSummary {
  'otherUserName' : string,
  'lastMessage' : string,
  'otherUser' : Principal,
  'lastTimestamp' : bigint,
}
export interface Message {
  'id' : bigint,
  'body' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : bigint,
}
export interface Post {
  'id' : bigint,
  'content' : string,
  'authorName' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : bigint,
  'comments' : Array<Comment>,
}
export interface PostOption { 'content' : string, 'style' : string }
export interface Profile {
  'bio' : string,
  'displayName' : string,
  'isPrivate' : boolean,
  'avatarUrl' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'isPrivate' : boolean,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string], bigint>,
  'generatePostOptions' : ActorMethod<[string], Array<PostOption>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getMyProfile' : ActorMethod<[], [] | [Profile]>,
  'getPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getPostsByUser' : ActorMethod<[Principal], Array<Post>>,
  'getProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], bigint>,
  'setProfile' : ActorMethod<[string, string, string, boolean], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];